export enum SigninCode {
  NO_USERNAME_OR_PASS = "NO_USERNAME_OR_PASS",
  NO_USER_WITH_EMAIL = "NO_USER_WITH_EMAIL",
  UNVERIFIED = "UNVERIFIED",
  INCORRECT_PASS = "INCORRECT_PASS",
  SERVER_ERROR = "SERVER_ERROR",
}
